from PyQt5 import QtCore, QtGui, QtWidgets

#Ну тут всякие дефолтные настройки, в общем ничего нового
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 851)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.List_of_commands = QtWidgets.QTableWidget(self.centralwidget)
        self.List_of_commands.setGeometry(QtCore.QRect(10, 460, 871, 331))
        self.List_of_commands.setObjectName("List_of_commands")
        self.List_of_commands.setColumnCount(0)
        self.List_of_commands.setRowCount(0)
        self.Adding = QtWidgets.QPushButton(self.centralwidget)
        self.Adding.setGeometry(QtCore.QRect(30, 10, 271, 71))
        self.Adding.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Adding.setObjectName("Adding")
        self.starting = QtWidgets.QPushButton(self.centralwidget)
        self.starting.setGeometry(QtCore.QRect(900, 620, 151, 71))
        self.starting.setObjectName("starting")
        self.delete = QtWidgets.QPushButton(self.centralwidget)
        self.delete.setGeometry(QtCore.QRect(900, 20, 151, 71))
        self.delete.setObjectName("delete")
        self.stopping = QtWidgets.QPushButton(self.centralwidget)
        self.stopping.setGeometry(QtCore.QRect(900, 710, 151, 71))
        self.stopping.setObjectName("stopping")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 0, 511, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(2)
        self.label.setMidLineWidth(6)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(560, 10, 311, 51))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 80, 511, 361))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(2)
        self.label_2.setMidLineWidth(6)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(560, 90, 311, 341))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Adding.setText(_translate("MainWindow", "Add command"))
        self.starting.setText(_translate("MainWindow", "Start"))
        self.delete.setText(_translate("MainWindow", """Delete\n(restart after deleting)"""))
        self.stopping.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Call Word"))
        self.label_2.setText(_translate("MainWindow", "Answer"))
